version: '3.9'

services:
  mongodb-dev:
    image: mongo:7.0.5
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - mongodb_data:/data/db
      - mongodb_logs:/var/log/mongodb
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - mongodb-network-dev

volumes:
  mongodb_data:
  mongodb_logs:
  redis_data:

networks:
  mongodb-network-dev:
    driver: bridge
