export const provinciasData = [
  {
    ProvCodi: 1,
    ProvNom: 'CHACHAPOYAS',
    depCode: 1,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 2,
    ProvNom: 'BAGUA',
    depCode: 1,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 3,
    ProvNom: 'BONGARA',
    depCode: 1,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 4,
    ProvNom: 'CONDORCANQUI',
    depCode: 1,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 5,
    ProvNom: 'LUYA',
    depCode: 1,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 6,
    ProvNom: 'RODRIGUEZ DE MENDO',
    depCode: 1,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 7,
    ProvNom: 'UTCUBAMBA',
    depCode: 1,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 8,
    ProvNom: 'HUARAZ',
    depCode: 2,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 9,
    ProvNom: 'AIJA',
    depCode: 2,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 10,
    ProvNom: 'ANTONIO RAYMONDI',
    depCode: 2,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 11,
    ProvNom: 'ASUNCION',
    depCode: 2,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 12,
    ProvNom: 'BOLOGNESI',
    depCode: 2,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 13,
    ProvNom: 'CARHUAZ',
    depCode: 2,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 14,
    ProvNom: 'CARLOS F. FITZCARRAL',
    depCode: 2,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 15,
    ProvNom: 'CASMA',
    depCode: 2,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 16,
    ProvNom: 'CORONGO',
    depCode: 2,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 17,
    ProvNom: 'HUARI',
    depCode: 2,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 18,
    ProvNom: 'HUARMEY',
    depCode: 2,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 19,
    ProvNom: 'HUAYLAS',
    depCode: 2,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 20,
    ProvNom: 'MARISCAL LUZURIAGA',
    depCode: 2,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 21,
    ProvNom: 'OCROS',
    depCode: 2,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 22,
    ProvNom: 'PALLASCA',
    depCode: 2,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 23,
    ProvNom: 'POMABAMBA',
    depCode: 2,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 24,
    ProvNom: 'RECUAY',
    depCode: 2,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 25,
    ProvNom: 'SANTA',
    depCode: 2,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 26,
    ProvNom: 'SIHUAS',
    depCode: 2,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 27,
    ProvNom: 'YUNGAY',
    depCode: 2,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 28,
    ProvNom: 'ABANCAY',
    depCode: 3,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 29,
    ProvNom: 'ANDAHUAYLAS',
    depCode: 3,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 30,
    ProvNom: 'ANTABAMBA',
    depCode: 3,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 31,
    ProvNom: 'AYMARAES',
    depCode: 3,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 32,
    ProvNom: 'COTABAMBAS',
    depCode: 3,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 33,
    ProvNom: 'CHINCHEROS',
    depCode: 3,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 34,
    ProvNom: 'GRAU',
    depCode: 3,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 35,
    ProvNom: 'AREQUIPA',
    depCode: 4,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 36,
    ProvNom: 'CAMANA',
    depCode: 4,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 37,
    ProvNom: 'CARAVELI',
    depCode: 4,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 38,
    ProvNom: 'CASTILLA',
    depCode: 4,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 39,
    ProvNom: 'CAYLLOMA',
    depCode: 4,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 40,
    ProvNom: 'CONDESUYOS',
    depCode: 4,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 41,
    ProvNom: 'ISLAY',
    depCode: 4,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 42,
    ProvNom: 'LA UNION',
    depCode: 4,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 43,
    ProvNom: 'HUAMANGA',
    depCode: 5,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 44,
    ProvNom: 'CANGALLO',
    depCode: 5,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 45,
    ProvNom: 'HUANCA SANCOS',
    depCode: 5,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 46,
    ProvNom: 'HUANTA',
    depCode: 5,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 47,
    ProvNom: 'LA MAR',
    depCode: 5,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 48,
    ProvNom: 'LUCANAS',
    depCode: 5,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 49,
    ProvNom: 'PARINACOCHAS',
    depCode: 5,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 50,
    ProvNom: 'PAUCAR DEL SARA SARA',
    depCode: 5,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 51,
    ProvNom: 'SUCRE',
    depCode: 5,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 52,
    ProvNom: 'VICTOR FAJARDO',
    depCode: 5,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 53,
    ProvNom: 'VILCAS HUAMAN',
    depCode: 5,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 54,
    ProvNom: 'CAJAMARCA',
    depCode: 6,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 55,
    ProvNom: 'CAJABAMBA',
    depCode: 6,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 56,
    ProvNom: 'CELENDIN',
    depCode: 6,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 57,
    ProvNom: 'CHOTA',
    depCode: 6,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 58,
    ProvNom: 'CONTUMAZA',
    depCode: 6,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 59,
    ProvNom: 'CUTERVO',
    depCode: 6,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 60,
    ProvNom: 'HUALGAYOC',
    depCode: 6,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 61,
    ProvNom: 'JAEN',
    depCode: 6,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 62,
    ProvNom: 'SAN IGNACIO',
    depCode: 6,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 63,
    ProvNom: 'SAN MARCOS',
    depCode: 6,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 64,
    ProvNom: 'SAN MIGUEL',
    depCode: 6,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 65,
    ProvNom: 'SAN PABLO',
    depCode: 6,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 66,
    ProvNom: 'SANTA CRUZ',
    depCode: 6,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 67,
    ProvNom: 'CALLAO',
    depCode: 7,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 68,
    ProvNom: 'CUSCO',
    depCode: 8,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 69,
    ProvNom: 'ACOMAYO',
    depCode: 8,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 70,
    ProvNom: 'ANTA',
    depCode: 8,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 71,
    ProvNom: 'CALCA',
    depCode: 8,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 72,
    ProvNom: 'CANAS',
    depCode: 8,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 73,
    ProvNom: 'CANCHIS',
    depCode: 8,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 74,
    ProvNom: 'CHUMBIVILCAS',
    depCode: 8,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 75,
    ProvNom: 'ESPINAR',
    depCode: 8,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 76,
    ProvNom: 'LA CONVENCION',
    depCode: 8,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 77,
    ProvNom: 'PARURO',
    depCode: 8,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 78,
    ProvNom: 'PAUCARTAMBO',
    depCode: 8,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 79,
    ProvNom: 'QUISPICANCHI',
    depCode: 8,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 80,
    ProvNom: 'URUBAMBA',
    depCode: 8,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 81,
    ProvNom: 'HUANCAVELICA',
    depCode: 9,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 82,
    ProvNom: 'ACOBAMBA',
    depCode: 9,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 83,
    ProvNom: 'ANGARAES',
    depCode: 9,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 84,
    ProvNom: 'CASTROVIRREYNA',
    depCode: 9,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 85,
    ProvNom: 'CHURCAMPA',
    depCode: 9,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 86,
    ProvNom: 'HUAYTARA',
    depCode: 9,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 87,
    ProvNom: 'TAYACAJA',
    depCode: 9,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 88,
    ProvNom: 'HUANUCO',
    depCode: 10,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 89,
    ProvNom: 'AMBO',
    depCode: 10,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 90,
    ProvNom: 'DOS DE MAYO',
    depCode: 10,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 91,
    ProvNom: 'HUACAYBAMBA',
    depCode: 10,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 92,
    ProvNom: 'HUAMALIES',
    depCode: 10,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 93,
    ProvNom: 'LEONCIO PRADO',
    depCode: 10,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 94,
    ProvNom: 'MARAÑON',
    depCode: 10,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 95,
    ProvNom: 'PACHITEA',
    depCode: 10,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 96,
    ProvNom: 'PUERTO INCA',
    depCode: 10,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 97,
    ProvNom: 'LAURICOCHA',
    depCode: 10,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 98,
    ProvNom: 'YAROWILCA',
    depCode: 10,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 99,
    ProvNom: 'ICA',
    depCode: 11,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 100,
    ProvNom: 'CHINCHA',
    depCode: 11,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 101,
    ProvNom: 'NAZCA',
    depCode: 11,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 102,
    ProvNom: 'PALPA',
    depCode: 11,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 103,
    ProvNom: 'PISCO',
    depCode: 11,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 104,
    ProvNom: 'HUANCAYO',
    depCode: 12,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 105,
    ProvNom: 'CONCEPCION',
    depCode: 12,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 106,
    ProvNom: 'CHANCHAMAYO',
    depCode: 12,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 107,
    ProvNom: 'JAUJA',
    depCode: 12,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 108,
    ProvNom: 'JUNIN',
    depCode: 12,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 109,
    ProvNom: 'SATIPO',
    depCode: 12,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 110,
    ProvNom: 'TARMA',
    depCode: 12,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 111,
    ProvNom: 'YAULI',
    depCode: 12,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 112,
    ProvNom: 'CHUPACA',
    depCode: 12,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 113,
    ProvNom: 'TRUJILLO',
    depCode: 13,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 114,
    ProvNom: 'ASCOPE',
    depCode: 13,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 115,
    ProvNom: 'BOLIVAR',
    depCode: 13,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 116,
    ProvNom: 'CHEPEN',
    depCode: 13,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 117,
    ProvNom: 'JULCAN',
    depCode: 13,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 118,
    ProvNom: 'OTUZCO',
    depCode: 13,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 119,
    ProvNom: 'PACASMAYO',
    depCode: 13,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 120,
    ProvNom: 'PATAZ',
    depCode: 13,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 121,
    ProvNom: 'SANCHEZ CARRION',
    depCode: 13,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 122,
    ProvNom: 'SANTIAGO DE CHUCO',
    depCode: 13,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 123,
    ProvNom: 'GRAN CHIMU',
    depCode: 13,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 124,
    ProvNom: 'VIRU',
    depCode: 13,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 125,
    ProvNom: 'CHICLAYO',
    depCode: 14,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 126,
    ProvNom: 'FERREÑAFE',
    depCode: 14,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 127,
    ProvNom: 'LAMBAYEQUE',
    depCode: 14,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 128,
    ProvNom: 'LIMA METROPOLITANA',
    depCode: 15,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 129,
    ProvNom: 'BARRANCA',
    depCode: 15,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 130,
    ProvNom: 'CAJATAMBO',
    depCode: 15,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 131,
    ProvNom: 'CANTA',
    depCode: 15,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 132,
    ProvNom: 'CAÑETE',
    depCode: 15,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 133,
    ProvNom: 'HUARAL',
    depCode: 15,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 134,
    ProvNom: 'HUAROCHIRI',
    depCode: 15,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 135,
    ProvNom: 'HUAURA',
    depCode: 15,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 136,
    ProvNom: 'OYON',
    depCode: 15,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 137,
    ProvNom: 'YAUYOS',
    depCode: 15,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 138,
    ProvNom: 'MAYNAS',
    depCode: 16,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 139,
    ProvNom: 'ALTO AMAZONAS',
    depCode: 16,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 140,
    ProvNom: 'LORETO',
    depCode: 16,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 141,
    ProvNom: 'MARISCAL RAMON CASTI',
    depCode: 16,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 142,
    ProvNom: 'REQUENA',
    depCode: 16,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 143,
    ProvNom: 'UCAYALI',
    depCode: 16,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 144,
    ProvNom: 'TAMBOPATA',
    depCode: 17,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 145,
    ProvNom: 'MANU',
    depCode: 17,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 146,
    ProvNom: 'TAHUAMANU',
    depCode: 17,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 147,
    ProvNom: 'MARISCAL NIETO',
    depCode: 18,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 148,
    ProvNom: 'GENERAL SANCHEZ CERR',
    depCode: 18,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 149,
    ProvNom: 'ILO',
    depCode: 18,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 150,
    ProvNom: 'PASCO',
    depCode: 19,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 151,
    ProvNom: 'DANIEL ALCIDES CARRI',
    depCode: 19,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 152,
    ProvNom: 'OXAPAMPA',
    depCode: 19,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 153,
    ProvNom: 'PIURA',
    depCode: 20,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 154,
    ProvNom: 'AYABACA',
    depCode: 20,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 155,
    ProvNom: 'HUANCABAMBA',
    depCode: 20,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 156,
    ProvNom: 'MORROPON',
    depCode: 20,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 157,
    ProvNom: 'PAITA',
    depCode: 20,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 158,
    ProvNom: 'SULLANA',
    depCode: 20,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 159,
    ProvNom: 'TALARA',
    depCode: 20,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 160,
    ProvNom: 'SECHURA',
    depCode: 20,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 161,
    ProvNom: 'PUNO',
    depCode: 21,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 162,
    ProvNom: 'AZANGARO',
    depCode: 21,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 163,
    ProvNom: 'CARABAYA',
    depCode: 21,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 164,
    ProvNom: 'CHUCUITO',
    depCode: 21,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 165,
    ProvNom: 'EL COLLAO',
    depCode: 21,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 166,
    ProvNom: 'HUANCANE',
    depCode: 21,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 167,
    ProvNom: 'LAMPA',
    depCode: 21,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 168,
    ProvNom: 'MELGAR',
    depCode: 21,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 169,
    ProvNom: 'MOHO',
    depCode: 21,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 170,
    ProvNom: 'SAN ANTONIO DE PUTIN',
    depCode: 21,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 171,
    ProvNom: 'SAN ROMAN',
    depCode: 21,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 172,
    ProvNom: 'SANDIA',
    depCode: 21,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 173,
    ProvNom: 'YUNGUYO',
    depCode: 21,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 174,
    ProvNom: 'MOYOBAMBA',
    depCode: 22,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 175,
    ProvNom: 'BELLAVISTA',
    depCode: 22,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 176,
    ProvNom: 'EL DORADO',
    depCode: 22,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 177,
    ProvNom: 'HUALLAGA',
    depCode: 22,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 178,
    ProvNom: 'LAMAS',
    depCode: 22,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 179,
    ProvNom: 'MARISCAL CACERES',
    depCode: 22,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 180,
    ProvNom: 'PICOTA',
    depCode: 22,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 181,
    ProvNom: 'RIOJA',
    depCode: 22,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 182,
    ProvNom: 'SAN MARTIN',
    depCode: 22,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 183,
    ProvNom: 'TOCACHE',
    depCode: 22,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 184,
    ProvNom: 'TACNA',
    depCode: 23,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 185,
    ProvNom: 'CANDARAVE',
    depCode: 23,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 186,
    ProvNom: 'JORGE BASADRE',
    depCode: 23,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 187,
    ProvNom: 'TARATA',
    depCode: 23,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 188,
    ProvNom: 'TUMBES',
    depCode: 24,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 189,
    ProvNom: 'CONTRALMIRANTE VILLA',
    depCode: 24,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 190,
    ProvNom: 'ZARUMILLA',
    depCode: 24,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 191,
    ProvNom: 'CORONEL PORTILLO',
    depCode: 25,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 192,
    ProvNom: 'ATALAYA',
    depCode: 25,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 193,
    ProvNom: 'PADRE ABAD',
    depCode: 25,
    __typename: 'Provincia',
  },
  {
    ProvCodi: 194,
    ProvNom: 'PURUS',
    depCode: 25,
    __typename: 'Provincia',
  },
];
